title: なんでも置き場
logo: /assets/img/logo.png
description: 2D obsessions.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
prof: |
 * 成人済み/雑食/CPより関係性
 * 頑張ってる女子が特に好きです
 * 型月．とある．物語シリーズ．逆転裁判．風花雪月．その他